# fly.toml app configuration file generated for bookclub-bot on 2023-11-01T21:12:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookclub-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"

[processes]
app = "node ./dist/src/run-bot.js"

